tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed": "#79f5ff",
                "tertiary-container": "#00f1ff",
                "on-secondary-fixed": "#1b1b1c",
                "tertiary-fixed-dim": "#00dbe8",
                "outline": "#999077",
                "error-container": "#93000a",
                "error": "#ffb4ab",
                "surface-container-highest": "#353534",
                "inverse-primary": "#705d00",
                "surface-container-high": "#2a2a2a",
                "on-surface": "#e5e2e1",
                "on-surface-variant": "#d0c6ab",
                "on-secondary-fixed-variant": "#474746",
                "surface-bright": "#393939",
                "tertiary": "#defcff",
                "background": "#131313",
                "surface-container": "#201f1f",
                "surface-dim": "#131313",
                "surface": "#131313",
                "primary-fixed-dim": "#e9c400",
                "surface-variant": "#353534",
                "primary-fixed": "#ffe16d",
                "primary": "#fff6df",
                "secondary": "#c8c6c5",
                "outline-variant": "#4d4732",
                "on-primary": "#3a3000",
                "surface-container-lowest": "#0e0e0e",
                "on-secondary-container": "#b7b5b4",
                "surface-container-low": "#1c1b1b",
                "secondary-fixed": "#e5e2e1",
                "primary-container": "#ffd700",
                "on-tertiary": "#00363a",
                "on-error-container": "#ffdad6",
                "secondary-container": "#474746",
                "on-primary-fixed-variant": "#544600",
                "inverse-surface": "#e5e2e1",
                "on-primary-fixed": "#221b00",
                "on-tertiary-fixed": "#002022",
                "on-primary-container": "#705e00",
                "on-secondary": "#303030",
                "on-background": "#e5e2e1",
                "surface-tint": "#e9c400",
                "inverse-on-surface": "#313030",
                "on-tertiary-fixed-variant": "#004f54",
                "on-tertiary-container": "#006a70",
                "on-error": "#690005",
                "secondary-fixed-dim": "#c8c6c5"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-desktop": "64px",
                "lg": "48px",
                "xs": "4px",
                "margin-mobile": "16px",
                "md": "24px",
                "base": "8px",
                "sm": "12px",
                "xl": "80px",
                "gutter": "20px"
            },
            "fontFamily": {
                "display-lg-mobile": ["Inter"],
                "label-sm": ["Inter"],
                "headline-sm": ["Inter"],
                "body-md": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
                "display-lg": ["Inter"],
                "label-md": ["Inter"]
            },
            "fontSize": {
                "display-lg-mobile": ["36px", { "lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
            }
        },
    },
}
